/*
YASM (Yet Another Skill Management) API

Testing AvailabilityApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_client_AvailabilityApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test AvailabilityApiService CreateAvailability", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var personId string

        resp, httpRes, err := apiClient.AvailabilityApi.CreateAvailability(context.Background(), personId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test AvailabilityApiService DeleteAvailability", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var personId string
        var availabilityId string

        resp, httpRes, err := apiClient.AvailabilityApi.DeleteAvailability(context.Background(), personId, availabilityId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test AvailabilityApiService GetAvailabilities", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var personId string

        resp, httpRes, err := apiClient.AvailabilityApi.GetAvailabilities(context.Background(), personId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test AvailabilityApiService UpdateAvailability", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var personId string
        var availabilityId string

        resp, httpRes, err := apiClient.AvailabilityApi.UpdateAvailability(context.Background(), personId, availabilityId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
