/*
YASM (Yet Another Skill Management) API

This is an example of using OAuth2 Implicit Flow in a specification to describe security to your API.

API version: 1.78.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the PagedProjectLayouts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PagedProjectLayouts{}

// PagedProjectLayouts struct for PagedProjectLayouts
type PagedProjectLayouts struct {
	Page
	ProjectLayouts []ProjectLayoutDetails `json:"projectLayouts,omitempty"`
}

// NewPagedProjectLayouts instantiates a new PagedProjectLayouts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPagedProjectLayouts() *PagedProjectLayouts {
	this := PagedProjectLayouts{}
	return &this
}

// NewPagedProjectLayoutsWithDefaults instantiates a new PagedProjectLayouts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPagedProjectLayoutsWithDefaults() *PagedProjectLayouts {
	this := PagedProjectLayouts{}
	return &this
}

// GetProjectLayouts returns the ProjectLayouts field value if set, zero value otherwise.
func (o *PagedProjectLayouts) GetProjectLayouts() []ProjectLayoutDetails {
	if o == nil || IsNil(o.ProjectLayouts) {
		var ret []ProjectLayoutDetails
		return ret
	}
	return o.ProjectLayouts
}

// GetProjectLayoutsOk returns a tuple with the ProjectLayouts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagedProjectLayouts) GetProjectLayoutsOk() ([]ProjectLayoutDetails, bool) {
	if o == nil || IsNil(o.ProjectLayouts) {
		return nil, false
	}
	return o.ProjectLayouts, true
}

// HasProjectLayouts returns a boolean if a field has been set.
func (o *PagedProjectLayouts) HasProjectLayouts() bool {
	if o != nil && !IsNil(o.ProjectLayouts) {
		return true
	}

	return false
}

// SetProjectLayouts gets a reference to the given []ProjectLayoutDetails and assigns it to the ProjectLayouts field.
func (o *PagedProjectLayouts) SetProjectLayouts(v []ProjectLayoutDetails) {
	o.ProjectLayouts = v
}

func (o PagedProjectLayouts) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PagedProjectLayouts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedPage, errPage := json.Marshal(o.Page)
	if errPage != nil {
		return map[string]interface{}{}, errPage
	}
	errPage = json.Unmarshal([]byte(serializedPage), &toSerialize)
	if errPage != nil {
		return map[string]interface{}{}, errPage
	}
	if !IsNil(o.ProjectLayouts) {
		toSerialize["projectLayouts"] = o.ProjectLayouts
	}
	return toSerialize, nil
}

type NullablePagedProjectLayouts struct {
	value *PagedProjectLayouts
	isSet bool
}

func (v NullablePagedProjectLayouts) Get() *PagedProjectLayouts {
	return v.value
}

func (v *NullablePagedProjectLayouts) Set(val *PagedProjectLayouts) {
	v.value = val
	v.isSet = true
}

func (v NullablePagedProjectLayouts) IsSet() bool {
	return v.isSet
}

func (v *NullablePagedProjectLayouts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePagedProjectLayouts(val *PagedProjectLayouts) *NullablePagedProjectLayouts {
	return &NullablePagedProjectLayouts{value: val, isSet: true}
}

func (v NullablePagedProjectLayouts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePagedProjectLayouts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


