/*
 * YASM (Yet Another Skill Management) API
 *
 * This is an example of using OAuth2 Implicit Flow in a specification to describe security to your API.
 *
 * API version: VERSION
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// CountryDetailsAllOf struct for CountryDetailsAllOf
type CountryDetailsAllOf struct {
	Languages *[]Language `json:"languages,omitempty"`
}

// NewCountryDetailsAllOf instantiates a new CountryDetailsAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCountryDetailsAllOf() *CountryDetailsAllOf {
	this := CountryDetailsAllOf{}
	return &this
}

// NewCountryDetailsAllOfWithDefaults instantiates a new CountryDetailsAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCountryDetailsAllOfWithDefaults() *CountryDetailsAllOf {
	this := CountryDetailsAllOf{}
	return &this
}

// GetLanguages returns the Languages field value if set, zero value otherwise.
func (o *CountryDetailsAllOf) GetLanguages() []Language {
	if o == nil || o.Languages == nil {
		var ret []Language
		return ret
	}
	return *o.Languages
}

// GetLanguagesOk returns a tuple with the Languages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CountryDetailsAllOf) GetLanguagesOk() (*[]Language, bool) {
	if o == nil || o.Languages == nil {
		return nil, false
	}
	return o.Languages, true
}

// HasLanguages returns a boolean if a field has been set.
func (o *CountryDetailsAllOf) HasLanguages() bool {
	if o != nil && o.Languages != nil {
		return true
	}

	return false
}

// SetLanguages gets a reference to the given []Language and assigns it to the Languages field.
func (o *CountryDetailsAllOf) SetLanguages(v []Language) {
	o.Languages = &v
}

func (o CountryDetailsAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Languages != nil {
		toSerialize["languages"] = o.Languages
	}
	return json.Marshal(toSerialize)
}

type NullableCountryDetailsAllOf struct {
	value *CountryDetailsAllOf
	isSet bool
}

func (v NullableCountryDetailsAllOf) Get() *CountryDetailsAllOf {
	return v.value
}

func (v *NullableCountryDetailsAllOf) Set(val *CountryDetailsAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCountryDetailsAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCountryDetailsAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCountryDetailsAllOf(val *CountryDetailsAllOf) *NullableCountryDetailsAllOf {
	return &NullableCountryDetailsAllOf{value: val, isSet: true}
}

func (v NullableCountryDetailsAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCountryDetailsAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


